"""empty message

Revision ID: 5f679d4909ed
Revises: 
Create Date: 2019-05-16 19:43:35.780242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f679d4909ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Styles',
    sa.Column('artistid', sa.Integer(), nullable=False),
    sa.Column('styleid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artistid'], ['artists.artistid'], onupdate='cascade'),
    sa.ForeignKeyConstraint(['styleid'], ['art_styles.styleid'], onupdate='cascade'),
    sa.PrimaryKeyConstraint('artistid', 'styleid')
    )
    op.create_table('artistPreference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artistid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artistid'], ['artists.artistid'], onupdate='cascade'),
    sa.ForeignKeyConstraint(['id'], ['customers.id'], onupdate='cascade'),
    sa.PrimaryKeyConstraint('id', 'artistid')
    )
    op.create_table('categoryPreference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoryid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoryid'], ['art_categories.categoryid'], onupdate='cascade'),
    sa.ForeignKeyConstraint(['id'], ['customers.id'], onupdate='cascade'),
    sa.PrimaryKeyConstraint('id', 'categoryid')
    )
    op.create_table('Categories',
    sa.Column('artworkid', sa.Integer(), nullable=False),
    sa.Column('categoryid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artworkid'], ['artworks.artworkid'], onupdate='cascade'),
    sa.ForeignKeyConstraint(['categoryid'], ['art_categories.categoryid'], onupdate='cascade'),
    sa.PrimaryKeyConstraint('artworkid', 'categoryid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Categories')
    op.drop_table('categoryPreference')
    op.drop_table('artistPreference')
    op.drop_table('Styles')
    # ### end Alembic commands ###
